[package]
name = "zova-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/zova-sys"
description = "Raw Rust FFI bindings for Zova's C ABI."
readme = "README.md"
keywords = ["zova", "sqlite", "ffi", "database"]
categories = ["database", "external-ffi-bindings"]
links = "zova"
build = "build.rs"
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "build.rs",
    "build_target.rs",
    "src/**",
    "tests/**",
    "tools/**",
]


[lib]
path = "src/lib.rs"

[build-dependencies]
cc = "1.2"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64", target_env = "gnu"))'.dependencies]
zova-sys-linux-x64 = { version = "=1.0.0-rc.3", path = "../zova-sys-linux-x64" }

[target.'cfg(all(target_os = "linux", target_arch = "aarch64", target_env = "gnu"))'.dependencies]
zova-sys-linux-arm64 = { version = "=1.0.0-rc.3", path = "../zova-sys-linux-arm64" }

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))'.dependencies]
zova-sys-darwin-x64 = { version = "=1.0.0-rc.3", path = "../zova-sys-darwin-x64" }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
zova-sys-darwin-arm64 = { version = "=1.0.0-rc.3", path = "../zova-sys-darwin-arm64" }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64", target_env = "msvc"))'.dependencies]
zova-sys-windows-x64 = { version = "=1.0.0-rc.3", path = "../zova-sys-windows-x64" }
