const std = @import("std");

pub const sqlite = @import("sqlite.zig");
const zova = @import("zova.zig");

pub const Database = zova.Database;
pub const Error = zova.Error;
pub const Object = zova.Object;
pub const ObjectChunk = zova.ObjectChunk;
pub const ObjectChunkData = zova.ObjectChunkData;
pub const ObjectChunkId = zova.ObjectChunkId;
pub const ObjectId = zova.ObjectId;
pub const ObjectManifest = zova.ObjectManifest;
pub const ObjectWriter = zova.ObjectWriter;
pub const Vector = zova.Vector;
pub const VectorCollectionInfo = zova.VectorCollectionInfo;
pub const VectorCollectionList = zova.VectorCollectionList;
pub const VectorCollectionOptions = zova.VectorCollectionOptions;
pub const VectorInput = zova.VectorInput;
pub const VectorMetric = zova.VectorMetric;
pub const VectorSearchResult = zova.VectorSearchResult;
pub const VectorSearchResults = zova.VectorSearchResults;
pub const Notification = zova.Notification;
pub const NotificationSubscription = zova.NotificationSubscription;
pub const OpenOptions = zova.OpenOptions;
pub const BackupOptions = zova.BackupOptions;
pub const CompactOptions = zova.CompactOptions;
pub const RestoreOptions = zova.RestoreOptions;
pub const max_vector_dimensions = zova.max_vector_dimensions;
pub const objectChunkId = zova.objectChunkId;
pub const objectId = zova.objectId;
pub const convertSqliteToZova = zova.convertSqliteToZova;
pub const restoreBackup = zova.restoreBackup;

test "package exports sqlite namespace" {
    try std.testing.expect(@hasDecl(@This(), "sqlite"));
    try std.testing.expect(@hasDecl(sqlite, "Database"));
    try std.testing.expect(@hasDecl(sqlite, "Statement"));
    try std.testing.expect(@hasDecl(sqlite, "c"));
}

test "package exports zova database namespace" {
    try std.testing.expect(@hasDecl(@This(), "Database"));
    try std.testing.expect(@hasDecl(@This(), "Error"));
    try std.testing.expect(@hasDecl(@This(), "OpenOptions"));
    try std.testing.expect(@hasDecl(@This(), "BackupOptions"));
    try std.testing.expect(@hasDecl(@This(), "CompactOptions"));
    try std.testing.expect(@hasDecl(@This(), "RestoreOptions"));
    try std.testing.expect(@hasDecl(@This(), "convertSqliteToZova"));
    try std.testing.expect(@hasDecl(@This(), "restoreBackup"));
    try std.testing.expect(@hasDecl(@This(), "Object"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunk"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunkData"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunkId"));
    try std.testing.expect(@hasDecl(@This(), "ObjectId"));
    try std.testing.expect(@hasDecl(@This(), "ObjectManifest"));
    try std.testing.expect(@hasDecl(@This(), "ObjectWriter"));
    try std.testing.expect(@hasDecl(@This(), "objectChunkId"));
    try std.testing.expect(@hasDecl(@This(), "objectId"));
    try std.testing.expect(@hasDecl(@This(), "Vector"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionInfo"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionList"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionOptions"));
    try std.testing.expect(@hasDecl(@This(), "VectorInput"));
    try std.testing.expect(@hasDecl(@This(), "VectorMetric"));
    try std.testing.expect(@hasDecl(@This(), "VectorSearchResult"));
    try std.testing.expect(@hasDecl(@This(), "VectorSearchResults"));
    try std.testing.expect(@hasDecl(@This(), "Notification"));
    try std.testing.expect(@hasDecl(@This(), "NotificationSubscription"));
    try std.testing.expect(@hasDecl(@This(), "max_vector_dimensions"));
    try std.testing.expectEqual(@as(usize, 32), @sizeOf(ObjectId));
    try std.testing.expectEqual(@as(usize, 32), @sizeOf(ObjectChunkId));
    try std.testing.expectEqual(@as(u32, 16_384), max_vector_dimensions);
    try std.testing.expect(@hasDecl(Database, "putObject"));
    try std.testing.expect(@hasDecl(Database, "getObject"));
    try std.testing.expect(@hasDecl(Database, "hasObject"));
    try std.testing.expect(@hasDecl(Database, "objectSize"));
    try std.testing.expect(@hasDecl(Database, "objectChunkCount"));
    try std.testing.expect(@hasDecl(Database, "deleteObject"));
    try std.testing.expect(@hasDecl(Database, "objectManifest"));
    try std.testing.expect(@hasDecl(Database, "hasObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "getObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "putObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "assembleObjectFromChunks"));
    try std.testing.expect(@hasDecl(Database, "deleteObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "readObjectRange"));
    try std.testing.expect(@hasDecl(Database, "objectWriter"));
    try std.testing.expect(@hasDecl(Database, "createVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "hasVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "vectorCollectionInfo"));
    try std.testing.expect(@hasDecl(Database, "listVectorCollections"));
    try std.testing.expect(@hasDecl(Database, "putVector"));
    try std.testing.expect(@hasDecl(Database, "putVectors"));
    try std.testing.expect(@hasDecl(Database, "getVector"));
    try std.testing.expect(@hasDecl(Database, "hasVector"));
    try std.testing.expect(@hasDecl(Database, "deleteVector"));
    try std.testing.expect(@hasDecl(Database, "deleteVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "searchVectors"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsIn"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsById"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdIn"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsInWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdInWithin"));
    try std.testing.expect(@hasDecl(Database, "openWithOptions"));
    try std.testing.expect(@hasDecl(Database, "setBusyTimeout"));
    try std.testing.expect(@hasDecl(Database, "lastInsertRowid"));
    try std.testing.expect(@hasDecl(Database, "changes"));
    try std.testing.expect(@hasDecl(Database, "totalChanges"));
    try std.testing.expect(@hasDecl(Database, "backupTo"));
    try std.testing.expect(@hasDecl(Database, "compactTo"));
    try std.testing.expect(@hasDecl(Database, "listen"));
    try std.testing.expect(@hasDecl(Database, "notify"));
    try std.testing.expect(!@hasDecl(@This(), "fastcdc"));
}

test {
    _ = @import("object_tests.zig");
    _ = @import("vector_tests.zig");
    _ = @import("vector_sql_tests.zig");
}
