const std = @import("std");

pub const sqlite = @import("sqlite.zig");
pub const version = @import("version.zig");
const zova = @import("zova.zig");

pub const Database = zova.Database;
pub const Error = zova.Error;
pub const FormatCompatibility = zova.FormatCompatibility;
pub const DatabaseFormatInfo = zova.DatabaseFormatInfo;
pub const probeDatabaseFormat = zova.probeDatabaseFormat;
pub const CreateOptions = zova.CreateOptions;
pub const Object = zova.Object;
pub const ObjectChunk = zova.ObjectChunk;
pub const ObjectChunkData = zova.ObjectChunkData;
pub const ObjectChunkId = zova.ObjectChunkId;
pub const ObjectId = zova.ObjectId;
pub const ObjectManifest = zova.ObjectManifest;
pub const ObjectWriter = zova.ObjectWriter;
pub const Vector = zova.Vector;
pub const VectorCollectionInfo = zova.VectorCollectionInfo;
pub const VectorCollectionList = zova.VectorCollectionList;
pub const VectorCollectionOptions = zova.VectorCollectionOptions;
pub const VectorElementType = zova.VectorElementType;
pub const VectorInput = zova.VectorInput;
pub const VectorMetric = zova.VectorMetric;
pub const VectorValuesConst = zova.VectorValuesConst;
pub const VectorValuesOwned = zova.VectorValuesOwned;
pub const VectorSearchResult = zova.VectorSearchResult;
pub const VectorSearchResults = zova.VectorSearchResults;
pub const Notification = zova.Notification;
pub const NotificationSubscription = zova.NotificationSubscription;
pub const KvPutEntry = zova.KvPutEntry;
pub const GraphTargetType = zova.GraphTargetType;
pub const GraphInfo = zova.GraphInfo;
pub const GraphList = zova.GraphList;
pub const GraphNodeInput = zova.GraphNodeInput;
pub const FreshGraphNodeInput = zova.FreshGraphNodeInput;
pub const GraphNode = zova.GraphNode;
pub const GraphEdgeInput = zova.GraphEdgeInput;
pub const FreshGraphEdgeInput = zova.FreshGraphEdgeInput;
pub const FreshGraphBuildProfile = zova.FreshGraphBuildProfile;
pub const GraphEdge = zova.GraphEdge;
pub const GraphNeighborDirection = zova.GraphNeighborDirection;
pub const GraphNeighborsOptions = zova.GraphNeighborsOptions;
pub const GraphNeighbor = zova.GraphNeighbor;
pub const GraphNeighborList = zova.GraphNeighborList;
pub const GraphWalkOptions = zova.GraphWalkOptions;
pub const GraphWalkDirectionOptions = zova.GraphWalkDirectionOptions;
pub const GraphWalkItem = zova.GraphWalkItem;
pub const GraphWalk = zova.GraphWalk;
pub const Extension = zova.Extension;
pub const ExtensionRegistry = zova.ExtensionRegistry;
pub const ExtensionManifest = zova.ExtensionManifest;
pub const ExtensionInfo = zova.ExtensionInfo;
pub const ExtensionList = zova.ExtensionList;
pub const ExtensionSalvageMode = zova.ExtensionSalvageMode;
pub const ExtensionSalvageContext = zova.ExtensionSalvageContext;
pub const ExtensionSalvageResult = zova.ExtensionSalvageResult;
pub const DynamicExtensionSet = zova.DynamicExtensionSet;
pub const DynamicExtensionTrustRecord = zova.DynamicExtensionTrustRecord;
pub const DynamicExtensionTrustedList = zova.DynamicExtensionTrustedList;
pub const DynamicExtensionTrustStoreOptions = zova.DynamicExtensionTrustStoreOptions;
pub const DynamicExtensionBundleInfo = zova.DynamicExtensionBundleInfo;
pub const DynamicExtensionOwnedRegistry = zova.DynamicExtensionOwnedRegistry;
pub const bundledExtensionRegistry = zova.bundledExtensionRegistry;
pub const salvageInstalledExtensions = zova.salvageInstalledExtensions;
pub const extension_dynamic = zova.extension_dynamic;
pub const OpenOptions = zova.OpenOptions;
pub const BackupOptions = zova.BackupOptions;
pub const BoundObjectStoreInfo = zova.BoundObjectStoreInfo;
pub const BoundVectorStoreInfo = zova.BoundVectorStoreInfo;
pub const BoundGraphStoreInfo = zova.BoundGraphStoreInfo;
pub const CompactOptions = zova.CompactOptions;
pub const RestoreOptions = zova.RestoreOptions;
pub const SplitObjectStoreCounts = zova.SplitObjectStoreCounts;
pub const SplitObjectStoreResult = zova.SplitObjectStoreResult;
pub const SplitVectorStoreCounts = zova.SplitVectorStoreCounts;
pub const SplitVectorStoreResult = zova.SplitVectorStoreResult;
pub const SplitGraphStoreCounts = zova.SplitGraphStoreCounts;
pub const SplitGraphStoreResult = zova.SplitGraphStoreResult;
pub const max_vector_dimensions = zova.max_vector_dimensions;
pub const objectChunkId = zova.objectChunkId;
pub const objectId = zova.objectId;
pub const convertSqliteToZova = zova.convertSqliteToZova;
pub const createObjectStore = zova.createObjectStore;
pub const createVectorStore = zova.createVectorStore;
pub const createGraphStore = zova.createGraphStore;
pub const restoreBackup = zova.restoreBackup;
pub const restoreBackupWithExtensions = zova.restoreBackupWithExtensions;
pub const migrateDatabase = zova.migrateDatabase;
pub const migrateDatabaseWithExtensions = zova.migrateDatabaseWithExtensions;
pub const MigrateOptions = zova.MigrateOptions;

test "package exports sqlite namespace" {
    try std.testing.expect(@hasDecl(@This(), "sqlite"));
    try std.testing.expect(@hasDecl(sqlite, "Database"));
    try std.testing.expect(@hasDecl(sqlite, "Statement"));
    try std.testing.expect(@hasDecl(sqlite, "c"));
}

test "package exports central version constants" {
    try std.testing.expectEqualStrings(version.package_version, version.abi_version_string);
    const abi_from_parts = try std.fmt.allocPrint(
        std.testing.allocator,
        "{}.{}.{}",
        .{ version.abi_version_major, version.abi_version_minor, version.abi_version_patch },
    );
    defer std.testing.allocator.free(abi_from_parts);
    try std.testing.expectEqualStrings(abi_from_parts, version.abi_version_string);
    try std.testing.expect(version.format_version.len > 0);
    try std.testing.expect(version.sqlite_version.len > 0);
    try std.testing.expect(version.minimum_zig_version.len > 0);
}

test "package exports zova database namespace" {
    try std.testing.expect(@hasDecl(@This(), "Database"));
    try std.testing.expect(@hasDecl(@This(), "Error"));
    try std.testing.expect(@hasDecl(@This(), "OpenOptions"));
    try std.testing.expect(@hasDecl(@This(), "BackupOptions"));
    try std.testing.expect(@hasDecl(@This(), "BoundObjectStoreInfo"));
    try std.testing.expect(@hasDecl(@This(), "BoundVectorStoreInfo"));
    try std.testing.expect(@hasDecl(@This(), "BoundGraphStoreInfo"));
    try std.testing.expect(@hasDecl(@This(), "CompactOptions"));
    try std.testing.expect(@hasDecl(@This(), "RestoreOptions"));
    try std.testing.expect(@hasDecl(@This(), "SplitObjectStoreCounts"));
    try std.testing.expect(@hasDecl(@This(), "SplitObjectStoreResult"));
    try std.testing.expect(@hasDecl(@This(), "SplitVectorStoreCounts"));
    try std.testing.expect(@hasDecl(@This(), "SplitVectorStoreResult"));
    try std.testing.expect(@hasDecl(@This(), "SplitGraphStoreCounts"));
    try std.testing.expect(@hasDecl(@This(), "SplitGraphStoreResult"));
    try std.testing.expect(@hasDecl(@This(), "convertSqliteToZova"));
    try std.testing.expect(@hasDecl(@This(), "createObjectStore"));
    try std.testing.expect(@hasDecl(@This(), "createVectorStore"));
    try std.testing.expect(@hasDecl(@This(), "createGraphStore"));
    try std.testing.expect(@hasDecl(@This(), "restoreBackup"));
    try std.testing.expect(@hasDecl(@This(), "restoreBackupWithExtensions"));
    try std.testing.expect(@hasDecl(@This(), "Object"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunk"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunkData"));
    try std.testing.expect(@hasDecl(@This(), "ObjectChunkId"));
    try std.testing.expect(@hasDecl(@This(), "ObjectId"));
    try std.testing.expect(@hasDecl(@This(), "ObjectManifest"));
    try std.testing.expect(@hasDecl(@This(), "ObjectWriter"));
    try std.testing.expect(@hasDecl(@This(), "objectChunkId"));
    try std.testing.expect(@hasDecl(@This(), "objectId"));
    try std.testing.expect(@hasDecl(@This(), "Vector"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionInfo"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionList"));
    try std.testing.expect(@hasDecl(@This(), "VectorCollectionOptions"));
    try std.testing.expect(@hasDecl(@This(), "VectorElementType"));
    try std.testing.expect(@hasDecl(@This(), "VectorInput"));
    try std.testing.expect(@hasDecl(@This(), "VectorMetric"));
    try std.testing.expect(@hasDecl(@This(), "VectorValuesConst"));
    try std.testing.expect(@hasDecl(@This(), "VectorValuesOwned"));
    try std.testing.expect(@hasDecl(@This(), "VectorSearchResult"));
    try std.testing.expect(@hasDecl(@This(), "VectorSearchResults"));
    try std.testing.expect(@hasDecl(@This(), "Notification"));
    try std.testing.expect(@hasDecl(@This(), "NotificationSubscription"));
    try std.testing.expect(@hasDecl(@This(), "GraphTargetType"));
    try std.testing.expect(@hasDecl(@This(), "GraphNode"));
    try std.testing.expect(@hasDecl(@This(), "GraphEdgeInput"));
    try std.testing.expect(@hasDecl(@This(), "GraphEdge"));
    try std.testing.expect(@hasDecl(@This(), "GraphNeighborList"));
    try std.testing.expect(@hasDecl(@This(), "GraphWalk"));
    try std.testing.expect(@hasDecl(@This(), "Extension"));
    try std.testing.expect(@hasDecl(@This(), "ExtensionRegistry"));
    try std.testing.expect(@hasDecl(@This(), "ExtensionManifest"));
    try std.testing.expect(@hasDecl(@This(), "ExtensionInfo"));
    try std.testing.expect(@hasDecl(@This(), "ExtensionList"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionSet"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionTrustRecord"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionTrustedList"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionTrustStoreOptions"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionBundleInfo"));
    try std.testing.expect(@hasDecl(@This(), "DynamicExtensionOwnedRegistry"));
    try std.testing.expect(@hasDecl(@This(), "bundledExtensionRegistry"));
    try std.testing.expect(@hasDecl(@This(), "extension_dynamic"));
    try std.testing.expect(@hasDecl(@This(), "max_vector_dimensions"));
    try std.testing.expectEqual(@as(usize, 32), @sizeOf(ObjectId));
    try std.testing.expectEqual(@as(usize, 32), @sizeOf(ObjectChunkId));
    try std.testing.expectEqual(@as(u32, 16_384), max_vector_dimensions);
    try std.testing.expect(@hasDecl(Database, "putObject"));
    try std.testing.expect(@hasDecl(Database, "getObject"));
    try std.testing.expect(@hasDecl(Database, "hasObject"));
    try std.testing.expect(@hasDecl(Database, "objectSize"));
    try std.testing.expect(@hasDecl(Database, "objectChunkCount"));
    try std.testing.expect(@hasDecl(Database, "deleteObject"));
    try std.testing.expect(@hasDecl(Database, "objectManifest"));
    try std.testing.expect(@hasDecl(Database, "hasObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "getObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "putObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "assembleObjectFromChunks"));
    try std.testing.expect(@hasDecl(Database, "deleteObjectChunk"));
    try std.testing.expect(@hasDecl(Database, "readObjectRange"));
    try std.testing.expect(@hasDecl(Database, "objectWriter"));
    try std.testing.expect(@hasDecl(Database, "createVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "hasVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "vectorCollectionInfo"));
    try std.testing.expect(@hasDecl(Database, "listVectorCollections"));
    try std.testing.expect(@hasDecl(Database, "putVector"));
    try std.testing.expect(@hasDecl(Database, "putVectors"));
    try std.testing.expect(@hasDecl(Database, "getVector"));
    try std.testing.expect(@hasDecl(Database, "hasVector"));
    try std.testing.expect(@hasDecl(Database, "deleteVector"));
    try std.testing.expect(@hasDecl(Database, "deleteVectorCollection"));
    try std.testing.expect(@hasDecl(Database, "searchVectors"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsIn"));
    try std.testing.expect(@hasDecl(Database, "searchMultiI8Cosine"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsById"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdIn"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsInWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdWithin"));
    try std.testing.expect(@hasDecl(Database, "searchVectorsByIdInWithin"));
    try std.testing.expect(@hasDecl(Database, "openWithOptions"));
    try std.testing.expect(@hasDecl(Database, "openForObjectStoreManagement"));
    try std.testing.expect(@hasDecl(Database, "setBusyTimeout"));
    try std.testing.expect(@hasDecl(Database, "lastInsertRowid"));
    try std.testing.expect(@hasDecl(Database, "changes"));
    try std.testing.expect(@hasDecl(Database, "totalChanges"));
    try std.testing.expect(@hasDecl(Database, "backupTo"));
    try std.testing.expect(@hasDecl(Database, "bindObjectStore"));
    try std.testing.expect(@hasDecl(Database, "boundObjectStore"));
    try std.testing.expect(@hasDecl(Database, "bindVectorStore"));
    try std.testing.expect(@hasDecl(Database, "boundVectorStore"));
    try std.testing.expect(@hasDecl(Database, "compactTo"));
    try std.testing.expect(@hasDecl(Database, "splitObjectStore"));
    try std.testing.expect(@hasDecl(Database, "splitVectorStore"));
    try std.testing.expect(!@hasDecl(Database, "rebindObjectStore"));
    try std.testing.expect(@hasDecl(Database, "unbindObjectStore"));
    try std.testing.expect(@hasDecl(Database, "unbindVectorStore"));
    try std.testing.expect(@hasDecl(Database, "listen"));
    try std.testing.expect(@hasDecl(Database, "notify"));
    try std.testing.expect(@hasDecl(Database, "createGraph"));
    try std.testing.expect(@hasDecl(Database, "listGraphs"));
    try std.testing.expect(@hasDecl(Database, "putGraphNodes"));
    try std.testing.expect(@hasDecl(Database, "putGraphEdges"));
    try std.testing.expect(@hasDecl(Database, "deleteGraphNodes"));
    try std.testing.expect(@hasDecl(Database, "graphDegree"));
    try std.testing.expect(@hasDecl(Database, "graphInfo"));
    try std.testing.expect(@hasDecl(Database, "putGraphNode"));
    try std.testing.expect(@hasDecl(Database, "getGraphNode"));
    try std.testing.expect(@hasDecl(Database, "putGraphEdge"));
    try std.testing.expect(@hasDecl(Database, "getGraphEdge"));
    try std.testing.expect(@hasDecl(Database, "graphNeighbors"));
    try std.testing.expect(@hasDecl(Database, "graphWalk"));
    try std.testing.expect(@hasDecl(Database, "graphWalkDirection"));
    try std.testing.expect(@hasDecl(Database, "createWithExtensions"));
    try std.testing.expect(@hasDecl(Database, "openWithExtensions"));
    try std.testing.expect(@hasDecl(Database, "openWithOptionsAndExtensions"));
    try std.testing.expect(@hasDecl(Database, "openForObjectStoreManagementWithExtensions"));
    try std.testing.expect(@hasDecl(Database, "installExtension"));
    try std.testing.expect(@hasDecl(Database, "listExtensions"));
    try std.testing.expect(@hasDecl(Database, "extensionInfo"));
    try std.testing.expect(@hasDecl(Database, "checkExtension"));
    try std.testing.expect(@hasDecl(Database, "dropExtension"));
    try std.testing.expect(!@hasDecl(@This(), "fastcdc"));
}
